import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { DM_Sans } from "next/font/google";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Platypus Outdoor Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable}bg-[#E0F7FA] antialiased min-h-screen hide-scrollbar`}
      >
        <div className="fixed inset-0 -z-10 bg-gradient-to-r from-[#E0F7FA] via-[#B3E5FC] to-[#81D4FA]" />
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
