import { Sora } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["400", "600", "700"],
});

export const metadata = {
  title: "Platypus Outdoor Solutions",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const h = await headers();
  const pathname = h.get("x-pathname") || h.get("next-url") || "";
  const isAdmin = pathname.startsWith("/admin");

  return (
    <html lang="en">
      <body
        className={`${sora.variable} bg-[#0B132B] antialiased min-h-screen hide-scrollbar overflow-x-hidden`}
      >
        {!isAdmin && <Navbar />}
        <main className="relative">{children}</main>
        {!isAdmin && <Footer />}
      </body>
    </html>
  );
}
